[tox]
envlist = py39,py310,py311,py312,py313,py314,lint

[gh]
python =
    3.14 = py314
    3.13 = py313
    3.12 = py312
    3.11 = py311
    3.10 = py310
    3.9 = py39

[testenv]
deps =
    responses
    pytest
    pytest-cov
    pytest-aiohttp
    pytest-asyncio
commands =
    pytest --cov=opencage_cli --cov-report=term-missing test

[testenv:lint]
usedevelop = True
deps =
    responses
    flake8>=7.0.0
    pytest
commands =
    flake8 opencage_cli test
